services:
  petstore-api:
    build:
      context: ./petstore-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v3/store/inventory"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api-tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      petstore-api:
        condition: service_healthy
    environment:
      - TEST_ENV=docker
    volumes:
      - ./reports:/app/reports