on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ 03-add-ci-workflow ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
